#include <stdio.h>
int main ()
{
	double height, flowrate, massflowrate, watts, Megawatts;
	double gravitationalconstant = 9.8;
	double efficiency = 0.90;
	printf("Enter the height of the dam");
	scanf("%lf", &height);
	printf("Enter the flowrate of water");
	scanf("%lf", &flowrate);
	massflowrate = flowrate * 1000;
	watts = efficiency * massflowrate * gravitationalconstant * height;
	Megawatts = watts / 1000000;
	printf("Power generated by the hydrolectric dam: %.2fMegawatts|n", Megawatts);

	return 0;
}
